//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Identity.Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityUserRole
    {
        public IdentityUserRole()
        {
            this.Users = new HashSet<IdentityUser>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<IdentityUser> Users { get; set; }
    }
}
